url: "https://tgragnato.it"
title: Tommaso Gragnato

markdown: kramdown
highlighter: rouge

sass:
  style: compressed
  sass_dir: _sass
  sourcemap: development

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

exclude:
  - _site
  - .sass-cache
  - .github
  - .jekyll-cache
  - .jekyll-metadata
  - vendor/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md
include:
  - .well-known

collections:

  snippets:
    output: false

  packages:
    output: true
    permalink: /:name/